//
//  LanguageGeneral.swift
//  RealHome
//
//  Created by boqian cheng on 2017-10-22.
//  Copyright © 2017 boqiancheng. All rights reserved.
//

import Foundation

struct LanguageGeneral {
    
    static var signInStr = "Sign In"
    static var cancelStr = "Cancel"
    static var logInStr = "Log In"
    static var logOutStr = "Log Out"
    static var backStr = "Back"
    static var forgotPWStr = "Forgot Password?"
    static var registerStr = "Register"
    static var emailStr = "Email"
    static var passwordStr = "Password"
    static var registerAsStr = "Register As"
    static var resetPasswordStr = "Reset Password"
    static var resetPWreminderStr = "Please enter your email address and we'll send you a link to reset your password."
    static var welcomeStr = "Welcome!"
    static var confirmPWStr = "Confirm password"
    static var bySigningStr1 = "By signing up, you are"
    static var bySigningStr2 = "agreeing to our"
    static var termsConditionsStr = "Terms and Conditions."
    
    static var enterAgentCodeStr = "Enter the code for your agent"
    static var enterAnotherAgentCodeStr = "Enter the code for another agent"
    static var enterYourAgentCodeStr = "Enter your agent code"
    static var toGetConnectedStr = "to get connected"
    static var applyForCodeStr = "Apply for a Code"
    static var toGetCommunicateStr = "to get communicate with your clients"
    static var enterStr = "Enter"
    static var orStr = "OR"
    
    static var languageStr = "Language"
    static var contactUsStr = "Contact Us"
    static var maleStr = "Male"
    static var femaleStr = "Female"
    static var agentCodeStr = "Agent Code"
    
    static var saveStr = "Save"
    static var notSaveStr = "Don't Save"
    static var addStr = "Add"
    
    // for applying agent code
    static var applyForAgentCodeStr = "Apply for Your Agent Code"
    static var theCodeMustBeStr = "The code must be exactly six digits long, and better be unique with different digits."
    static var codeStr = "Code"
    static var applyStr = "Apply"
    static var hasBeenTakenStr = " has been taken, and try another one."
    static var isPerfectStr = " is perfect."
    
    static var thankYouForUsingStr = "Thank you for using"
    
    static var pleaseEmailUsIssueStr = "Please email us for any issue."
    static var emailUsStr = "Email Us"
    static var reportIssuesStr = "Report issues"
    static var reportHereStr = "Report here"
    static var deviceCantSendEmailStr = "This device cannot send email, please configure it."
    
    static var selectYourLangaugeStr = "Select Your Language"
    
    static var yourPersonalInfoStr = "Your Personal Info"
    static var firstNameStr = "First Name"
    static var lastNameStr = "Last Name"
    static var nickNameStr = "Nick Name"
    static var nickNameShortStr = "(Nick)Name"
    static var genderStr = "Gender"
    static var phoneStr = "Phone"
    static var nameStr = "Name"
    static var yourNameStr = "Your (Nick)Name"
    static var yourEmailStr = "Your email"
    static var yourPhoneStr = "Your phone"
    
    static var chooseFromAlbumStr = "Choose from Albums"
    static var takePhotoStr = "Take Photo"
    static var photoAlbumsStr = "Photo Albums"
    
    static var searchStr = "Search"
    static var favoriteStr = "Favorites"
    static var settingStr = "Settings"
    static var buyerSingleStr = "Buyer"
    static var buyerStr = "Buyers"
    static var agentStr = "Agent"
    static var yourAgentsStr = "Your Agents"
    static var contactAgentStr = "Contact Agent"
    static var connectBuyersStr = "Connect Buyers"
    
    static var connectServerStr = "Connecting server..."
    static var okStr = "OK"
    static var doneStr = "Done"
    
    static var messages = "Messages"
    static var recommendations = "Recommendations"
    static var posts = "Posts"
    static var services = "Services"
    
    static var sendStr = "SEND"
    
    static var addAServiceStr = "Add a Service"
    static var expertiseStr = "Expertise"
    static var imageStr = "Image"
    static var addAPostStr = "Add a Post Link"
    static var withHTTPStr = "(full link with such as http://)"
    static var titleStr = "Title"
    static var briefingStr = "Briefing"
    static var webUrlStr = "URL (full link with such as http://)"
    static var addARecommendationStr = "Add a Recommendation"
    static var deleteStr = "Delete?"
    
    static var moreInfoStr = "More Info"
    static var schoolNearbyStr = "Schools Nearby"
    
    static var errMsgRestartApp = "Something wrong, please re-start app!"
    static var errMsgNotRightEmailFormat = "Not right email format."
    static var errMsgPasswordShort = "Password must be at least 5 characters."
    static var errMsgPWEmailEmpty = "Email and/or password can't be empty."
    static var errMsgProvideEmail = "Please provide a email address."
    static var errMsgSentEmailResetPW = "We've sent you an email with a link to reset your password."
    static var errMsgPWnotConfirm = "Confirmed password not match!"
    static var errMsgCantLogin = "Can't login, register first or check email and password and try again."
    static var errMsgNoSuchCode = "No such agent code"
    static var errMsgYouMaySetLater = "You may add later"
    static var errMsgUnknow = "Something wrong, please go back and try again."
    static var errMsgTryAgainStr = "Something wrong, try again."
    static var errMsgLeavingWithoutSaveStr = "Leaving without saving?"
    static var errMsgVideoNotSupportStr = "Video not Supported"
    static var errMsgWrongSiteURLStr = "Wrong web site address."
    static var errMsgNeedAllFieldsStr = "Input all fields."
    static var errMsgNoInputStr = "No input."
    static var errMsgNetworkErrorStr = "Network error, or no network connection."
    static var errMsgProvideYourEmail = "Please provide your email."
    static var errMsgNoMsgToSend = "No message to send!"
    static var errMsgProvideYourName = "Please provide your name."
    static var errMsgCannotOpenWebStr = "Can not open web site."
    static var errMsgContainsHttpStr = "Web URL must contain http:// or https://."
    
    static func setLang(Lang: String) {
        if Lang == englishStr {
            signInStr = "Sign In"
            cancelStr = "Cancel"
            logInStr = "Log In"
            logOutStr = "Log Out"
            backStr = "Back"
            forgotPWStr = "Forgot Password?"
            registerStr = "Register"
            emailStr = "Email"
            passwordStr = "Password"
            registerAsStr = "Register As"
            resetPasswordStr = "Reset Password"
            resetPWreminderStr = "Please enter your email address and we'll send you a link to reset your password."
            welcomeStr = "Welcome!"
            confirmPWStr = "Confirm password"
            bySigningStr1 = "By signing up, you are"
            bySigningStr2 = "agreeing to our"
            termsConditionsStr = "Terms and Conditions."
            
            enterAgentCodeStr = "Enter the code for your agent"
            enterAnotherAgentCodeStr = "Enter the code for another agent"
            enterYourAgentCodeStr = "Enter your agent code"
            toGetConnectedStr = "to get connected"
            applyForCodeStr = "Apply for a Code"
            toGetCommunicateStr = "to get communicate with your clients"
            enterStr = "Enter"
            orStr = "OR"
            
            languageStr = "Language"
            contactUsStr = "Contact Us"
            maleStr = "Male"
            femaleStr = "Female"
            agentCodeStr = "Agent Code"
            
            saveStr = "Save"
            notSaveStr = "Don't Save"
            addStr = "Add"
            
            // for applying agent code
            applyForAgentCodeStr = "Apply for Your Agent Code"
            theCodeMustBeStr = "The code must be exactly six digits long, and better be unique with different digits."
            codeStr = "Code"
            applyStr = "Apply"
            hasBeenTakenStr = " has been taken, and try another one."
            isPerfectStr = " is perfect."
            
            thankYouForUsingStr = "Thank you for using"
            
            pleaseEmailUsIssueStr = "Please email us for any issue."
            emailUsStr = "Email Us"
            reportIssuesStr = "Report issues"
            reportHereStr = "Report here"
            deviceCantSendEmailStr = "This device cannot send email, please configure it."
            
            selectYourLangaugeStr = "Select Your Language"
            
            yourPersonalInfoStr = "Your Personal Info"
            firstNameStr = "First Name"
            lastNameStr = "Last Name"
            nickNameStr = "Nick Name"
            nickNameShortStr = "(Nick)Name"
            genderStr = "Gender"
            phoneStr = "Phone"
            nameStr = "Name"
            yourNameStr = "Your (Nick)Name"
            yourEmailStr = "Your email"
            yourPhoneStr = "Your phone"
            
            chooseFromAlbumStr = "Choose from Albums"
            takePhotoStr = "Take Photo"
            photoAlbumsStr = "Photo Albums"
            
            searchStr = "Search"
            favoriteStr = "Favorites"
            settingStr = "Settings"
            buyerSingleStr = "Buyer"
            buyerStr = "Buyers"
            agentStr = "Agent"
            yourAgentsStr = "Your Agents"
            contactAgentStr = "Contact Agent"
            connectBuyersStr = "Connect Buyers"
            
            connectServerStr = "Connecting server..."
            okStr = "OK"
            doneStr = "Done"
            
            messages = "Messages"
            recommendations = "Recommendations"
            posts = "Posts"
            services = "Services"
            
            sendStr = "SEND"
            
            addAServiceStr = "Add a Service"
            expertiseStr = "Expertise"
            imageStr = "Image"
            addAPostStr = "Add a Post Link"
            withHTTPStr = "(full link with such as http://)"
            titleStr = "Title"
            briefingStr = "Briefing"
            webUrlStr = "URL (full link with such as http://)"
            addARecommendationStr = "Add a Recommendation"
            deleteStr = "Delete?"
            
            moreInfoStr = "More Info"
            schoolNearbyStr = "Schools Nearby"
            
            errMsgRestartApp = "Something wrong, please re-start app!"
            errMsgNotRightEmailFormat = "Not right email format."
            errMsgPasswordShort = "Password must be at least 5 characters."
            errMsgPWEmailEmpty = "Email and/or password can't be empty."
            errMsgProvideEmail = "Please provide a email address."
            errMsgSentEmailResetPW = "We've sent you an email with a link to reset your password."
            errMsgPWnotConfirm = "Confirmed password not match!"
            errMsgCantLogin = "Can't login, register first or check email and password and try again."
            errMsgNoSuchCode = "No such agent code"
            errMsgYouMaySetLater = "You may add later"
            errMsgUnknow = "Something wrong, please go back and try again."
            errMsgTryAgainStr = "Something wrong, try again."
            errMsgLeavingWithoutSaveStr = "Leaving without saving?"
            errMsgVideoNotSupportStr = "Video not Supported"
            errMsgWrongSiteURLStr = "Wrong web site address."
            errMsgNeedAllFieldsStr = "Input all fields."
            errMsgNoInputStr = "No input."
            errMsgNetworkErrorStr = "Network error, or no network connection."
            errMsgProvideYourEmail = "Please provide your email."
            errMsgNoMsgToSend = "No message to send!"
            errMsgProvideYourName = "Please provide your name."
            errMsgCannotOpenWebStr = "Can not open web site."
            errMsgContainsHttpStr = "Web URL must contain http:// or https://."
        } else if Lang == chineseStr {
            signInStr = "登录"
            cancelStr = "取消"
            logInStr = "登录"
            logOutStr = "登出"
            backStr = "回退"
            forgotPWStr = "忘记密码?"
            registerStr = "注册"
            emailStr = "电邮"
            passwordStr = "密码"
            registerAsStr = "注册为"
            resetPasswordStr = "重置密码"
            resetPWreminderStr = "请给出您的电邮，我们电邮您一个链接，以便您重置您的密码。"
            welcomeStr = "欢迎!"
            confirmPWStr = "确认密码"
            bySigningStr1 = "注册本应用程序，表示"
            bySigningStr2 = "您同意我们的"
            termsConditionsStr = "服务条款"
            
            enterAgentCodeStr = "输入您经纪的代码"
            enterAnotherAgentCodeStr = "输入您的另一个经纪代码"
            enterYourAgentCodeStr = "输入您的经纪代码"
            toGetConnectedStr = "以便建立联系"
            applyForCodeStr = "申请代码"
            toGetCommunicateStr = "方便与您的客户交流"
            enterStr = "输入"
            orStr = "或"
            
            languageStr = "语言"
            contactUsStr = "联系我们"
            maleStr = "男"
            femaleStr = "女"
            agentCodeStr = "经纪代码"
            
            saveStr = "保存"
            notSaveStr = "不保存"
            addStr = "添加"
            
            // for applying agent code
            applyForAgentCodeStr = "申请您的经纪代码"
            theCodeMustBeStr = "代码必须刚好是6个数字长，最好用不同的数字，则可唯一。"
            codeStr = "代码"
            applyStr = "申请"
            hasBeenTakenStr = "已被使用，尝试另一个。"
            isPerfectStr = "完美。"
            
            thankYouForUsingStr = "谢谢您使用"
            
            pleaseEmailUsIssueStr = "若有任何问题，请电邮我们。"
            emailUsStr = "电邮我们"
            reportIssuesStr = "报告问题"
            reportHereStr = "在此输入问题"
            deviceCantSendEmailStr = "您的设备不能发电邮，请设置电邮功能。"
            
            selectYourLangaugeStr = "选择语言"
            
            yourPersonalInfoStr = "您个人信息"
            firstNameStr = "名"
            lastNameStr = "姓"
            nickNameStr = "昵称"
            nickNameShortStr = "(昵)名"
            genderStr = "性别"
            phoneStr = "电话"
            nameStr = "姓名"
            yourNameStr = "您的(别)名"
            yourEmailStr = "您的电邮"
            yourPhoneStr = "您的电话"
            
            chooseFromAlbumStr = "相册"
            takePhotoStr = "相机"
            photoAlbumsStr = "相册"
            
            searchStr = "搜索"
            favoriteStr = "收藏"
            settingStr = "设置"
            buyerSingleStr = "置屋者"
            buyerStr = "置屋者"
            agentStr = "经纪"
            yourAgentsStr = "您的经纪"
            contactAgentStr = "联系经纪"
            connectBuyersStr = "连结买家"
            
            connectServerStr = "正在连接服务器..."
            okStr = "好"
            doneStr = "完成"
            
            messages = "短信"
            recommendations = "推荐"
            posts = "文章"
            services = "服务商家"
            
            sendStr = "发送"
            
            addAServiceStr = "添加商家"
            expertiseStr = "服务专业"
            imageStr = "像"
            addAPostStr = "添加文章链接"
            withHTTPStr = "(全链接，包含例如 http://)"
            titleStr = "标题"
            briefingStr = "简介"
            webUrlStr = "网址 (全链接，包含例如 http://)"
            addARecommendationStr = "添加推荐"
            deleteStr = "删除？"
            
            moreInfoStr = "更多信息"
            schoolNearbyStr = "附近学校"
            
            errMsgRestartApp = "发生未知问题，请重新启动本应用程序!"
            errMsgNotRightEmailFormat = "电邮箱格式不正确。"
            errMsgPasswordShort = "密码至少5位字符。"
            errMsgPWEmailEmpty = "电邮箱和密码不能为空。"
            errMsgProvideEmail = "请提供电邮箱地址。"
            errMsgSentEmailResetPW = "我们已电邮链接给您，请重置密码。"
            errMsgPWnotConfirm = "确认密码不正确!"
            errMsgCantLogin = "不能登录，先注册或检查email和密码后重试。"
            errMsgNoSuchCode = "没有此经纪代码"
            errMsgYouMaySetLater = "你可以晚些添加"
            errMsgUnknow = "发生未知问题，请回退，重试。"
            errMsgTryAgainStr = "发生未知问题，请重试。"
            errMsgLeavingWithoutSaveStr = "没有保存，确认退出本页?"
            errMsgVideoNotSupportStr = "不支持视频。"
            errMsgWrongSiteURLStr = "错误的网站地址。"
            errMsgNeedAllFieldsStr = "请输入所有信息。"
            errMsgNoInputStr = "没有输入。"
            errMsgNetworkErrorStr = "网络错误，或无网络连接。"
            errMsgProvideYourEmail = "请提供您的电邮。"
            errMsgNoMsgToSend = "无内容发送！"
            errMsgProvideYourName = "请提供您的姓名。"
            errMsgCannotOpenWebStr = "打不开网页。"
            errMsgContainsHttpStr = "网址URL需包含http:// 或 https://。"
        }
    }
}

